### ISSUE TITLE
error in eval_xg3_series() when applied to the droogtemeetnet workflow on a specific Windows machine

### ISSUE THREAD

**Issue by w-jan** [inbo/watina#6] opened 2019-07-25 12:53 UTC
executing sink(tempfile()) generates on my laptop this error:
_Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'Boundary_Crossing_Time.txt': Permission denied_

Maybe it can be omitted ??

**Comment by florisvdh** [comment] 2019-07-25 13:19
Hmmm, this should not happen, checked it on my colleague's Windows installation, where it works.

Omitting it would yield a large number of unneeded messages from the `disc_ks_test()` function, called by `eval_xg3_series()`. In essence, `sink(...)` opens a connection to a temporary file where those messages are redirected instead of appearing in the console. The temporary file should reside in a folder which is cleaned afterwards.

What is your output of this script:

```r
tf <- tempfile()
tf
file.create(tf)
sink(tf)
sink()
```

**Comment by w-jan** [comment] 2019-07-25 13:43
Further examination gives a blurred pattern: most of the times i get the same error, but when i repeat the execution of ' xg3_series_props <-
   series_memberyrs %>%
   group_by(.data$loc_code,
            .data$xg3_variable,
            .data$series) %>%
   summarise(
     ser_length = first(.data$series_length),
     ser_nryears = n(),
     ser_rel_nryears = .data$ser_nryears / .data$ser_length,
     ser_firstyear = min(.data$hydroyear),
     ser_lastyear = max(.data$hydroyear),
     ser_pval_uniform = disc_ks_test(.data$hydroyear,
                                     ecdf(seq(.data$ser_firstyear,
                                              .data$ser_lastyear)),
                                     exact = TRUE) %>%
       .$p.value
   ) %>%
   ungroup'
sometimes it works, but mostly doesn't.
My conclusion that sink-function was responsible for the error is therefor wrong. 

The output of the tf-script was nothing, but no errors.

On my windows-laptop the disc_ks_test()-function doesn't yield any message (also when i ignored the sink (tempfile())-commando.

**Comment by florisvdh** [comment] 2019-07-26 07:30
@w-jan referring to [your workflow](https://github.com/w-jan/Droogtemeetnet/blob/c2951730266e918b00e8988683357296ab536115/src/tube_selection.Rmd) I reproduced `tubes_xg3` and had no problems in obtaining the result of `eval_xg3_series()`, which you named `tubes_xg3_eval`.

Attached is an RData file with which you can load both tibbles that I generated 
(use `load("tubes.RData")`), especially in order to first check the equivalence of `tubes_xg3` with your case. I added a suffix `_fv` to the object names to keep things clear. Can you check the equivalence of the data sets?

[tubes.RData.zip](https://github.com/inbo/watina/files/3434700/tubes.RData.zip)

**Comment by florisvdh** [comment] 2019-07-26 08:59
@w-jan I could reproduce everything in a Windows installation as well (I normally do this in Linux), yielding the same results (apart from negligible digits from the 15th decimal position and further, in just 4 series, for `ser_pval_uniform` in `tubes_xg3_eval`).

So I think your problem is specific to your machine.

[Attached](https://github.com/inbo/watina/files/3434979/sessioninfo.txt) you find my output of `sessioninfo::session_info()` so that you can compare if package versions are the problem.

**Comment by w-jan** [comment] 2019-07-26 14:34
disc_ks_test causes the problem on my windows. The sink-commando's do their job.
Sometimes disc_ks_test works, sometimes not. A possible explanation: the function generates some random  series, sometimes they yield a solution, but sometimes not.
possible solution: change the uniformity-check as an option ? I'll give it a try

**Comment by w-jan** [comment] 2019-07-26 14:37
Oh, I didn't see your suggestions. I'll try them first

**Comment by florisvdh** [comment] 2019-07-26 15:40
> possible solution: change the uniformity-check as an option

make it optional in `eval_xg3()` is indeed a possible workaround, but rather last resort I think, especially given that this (currently?) seems to only occur on your machine. The option would then also need to be present in `selectlocs_xg3()`, which is able to call `eval_xg3()`.

**Comment by w-jan** [comment] 2019-07-26 16:12
I did the two checks.
Your object tubes_xg3_eval_fv is the same as mine (sometimes the disc-function works)
[My sessioninfo](https://github.com/inbo/watina/files/3436547/sessioninfo_jw.txt)
differs obviously, but i can't say if there's a structural problem. KSgeneral is the same. 
I see that although I updated the packages recently, the R-version isn't renewed.

**Comment by florisvdh** [comment] 2019-07-27 13:16
I saw from your sessioninfo that you use 32-bits R while my windows-test used 64-bits R. However, now trying with 32-bits R works equally fine; I tried it repeatedly.

Not knowing where your problem comes from (I can't reproduce it), I'd suggest you check the RStudio options ([here](https://inbo.github.io/tutorials/installation/user/user_install_rstudio/)) and/or reinstall your RStudio+R setup (but even then, it is questionable whether the problem lies there, it could also be some setting in your Windows-setup, ...). The fact that it sometimes works and sometimes not, may also be due to some hardware failure.

You could also do it on someone else's PC. I think there should at least be another independent case with this problem to make it worth adding an extra argument in two functions to cope with that. Agree?

You could also make a local branch of `watina`, omit the specific statistic where you get stuck, and locally install the package with `devtools::install(build_vignettes = TRUE)`. And keep your tweaked version up to date with master ;-) But I wouldn't recommend this tailored approach.

**Comment by florisvdh** [comment] 2019-08-05 13:42
Closing here. If other users would have this problem, a new issue can be made.

**Closed by florisvdh** 2019-08-05 13:42 UTC
